### ISSUE TITLE
Add question modal does not scroll

### ISSUE THREAD

**Issue by slichlyter12** [slichlyter12/CS561-Project#24]
When adding a new question, it is not possible to scroll down to hit the submit button

**Comment by glitterlee** [comment]
already fixed

**Comment by slichlyter12** [comment]
Only fixed for Chrome on Windows. See: https://github.com/slichlyter12/CS561-Project/pull/25

**Comment by glitterlee** [comment]
OK, I will test it on Mac

**Comment by glitterlee** [comment]
I just test it on the Mac in the library. It works on Chrome, Firefox, or Safari on MacOS. 
Can anyone test it on your MacOS again?

**Comment by slichlyter12** [comment]
Can you tell what version of MacOS they're running?

**Comment by glitterlee** [comment]
OS X EI Capitan Version 10.11.6

**Comment by glitterlee** [comment]
Firefox on Windows works on my laptop as well

**Comment by slichlyter12** [comment]
Weird. Well if it’s just my machine then we’re fine. I’ll do some more research when I get back to the office.

**Comment by DeqingQu** [comment]
In my Chrome, it still can't scroll. Chrome 63.0, Mac OS 10.13.2. 
Is it the latest version on Sam's server?

**Comment by slichlyter12** [comment]
Yeah, the server has the latest changes.

**Comment by glitterlee** [comment]
Weird. Could you clear cache and cookies and test again?

I am free this afternoon, I can sit with you and fix it.

**Comment by slichlyter12** [comment]
I did that and it worked when I enabled scroll bars to show up always, which I don't think is the default for MacOS. And the scroll wheel still does not work. This might be a bigger issue than originally thought. I'm not sure I'll have time to look into this this week, but my initial guess is it has something to do with how we're using React.

**Comment by glitterlee** [comment]
Unfortunately, it can not repeat on my laptop and MacOS in the library, so I can not find real causes. But, I will move on to find other solutions to fix it and try to borrow a Mac PC from my friends to test it. I will try to guarantee it will work on both Windows and MacOS at least for Chrome.

**Comment by glitterlee** [comment]
I fix this bug and test it on Mac. I think it works now. Can any guy test on your Mac as well?

**Comment by slichlyter12** [comment]
Fixed in fd6a2943134f721d0be992a356f582d68dfb3349
