### ISSUE TITLE
Class information Modification doesn't work in Admin Dashboard

### ISSUE THREAD

**Issue by DeqingQu** [slichlyter12/CS561-Project#43]
In Admin dashboard, if you click the class button, the 'class name and class code' input in prompt is 'undefined' and the input of 'adding ta' is empty. After I modify the content in prompt, it doesn't modify the class information correctly.
<img width="833" alt="screen shot 2018-02-23 at 4 20 14 pm" src="https://user-images.githubusercontent.com/2810578/36623033-147b5c60-18b6-11e8-91a0-f2afe4281824.png">

**Comment by glitterlee** [comment]
Weird, I just test on our server, it works fine. Did you test on your own server?
![image](https://user-images.githubusercontent.com/8252519/36623294-333e6b0e-18b8-11e8-989f-2d8813a72357.png)

**Comment by DeqingQu** [comment]
It may be caused by the conflict of the roles of user. When I (role == 2) add myself to be a TA, it happens.

**Comment by glitterlee** [comment]
Oh, yeah, it could be some permissions check
